### ISSUE TITLE
SHACL minInclusive not working for any numeric type other than xsd:integer 

### ISSUE THREAD

**Issue by MFSY** [labra/shaclex#105]
Hi,
I've tried to validate a double value by checking that it is between a minInclusive and maxInclusive value as shown below. 

Prefix mappings:
```
prefix :       <http://example.org/> 
prefix sh:     <http://www.w3.org/ns/shacl#> 
prefix xsd:    <http://www.w3.org/2001/XMLSchema#>
prefix schema: <http://schema.org/>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
```
data

```
:echotime  a schema:QuantitativeValue ;
        schema:unitCode  "second" ;
        schema:value     "0.002996"^^xsd:double .
```

shape:

```
schema:QuantitativeValue a sh:NodeShape, rdfs:Class ;
   sh:nodeKind sh:IRI ;
   sh:property [
    sh:path schema:value ; 
    sh:minCount 1; 
    sh:maxCount 1;
    sh:datatype xsd:double ;
    sh:minInclusive 0.001 ;
    sh:maxInclusive 0.01 ;
  ] .

```

But I got the following error:

```
"valid": false,
  "type": "Result",
  "message": "Not valid",
  "shapeMap": "No solutions",
  "errors": [
    {
      "type": "ErrorInfo",
      "error": "sh:notNumericError FocusNode: \"0.002996\"^^<http://www.w3.org/2001/XMLSchema#double> NotNumeric violation. Expected \"0.002996\"^^<http://www.w3.org/2001/XMLSchema#double> to be a number Node: <http://example.org/echotime>, Constraint: _:f92ea4e9dfea4c6b207b56bc9fb9c96c, path: PredicatePath(<http://schema.org/value>)"
    }
  ]
```

While a xsd:decimal as schema:value type pass the validation:

data
```
:echotime  a schema:QuantitativeValue ;
        schema:unitCode  "second" ;
        schema:value     "0.002996"^^xsd:decimal .
```

An untyped schema:value also pass the validation:

data
```
:echotime  a schema:QuantitativeValue ;
        schema:unitCode  "second" ;
        schema:value     0.002996 .
```

I've looked at the code and performed some debug. Here are what I've seen as potential sources of the above issues (please correct me if I'm wrong):

1. Looking at  the code at [JenaMapper.jenaNode2RDFNode(r: JenaRDFNode): RDFNode](https://github.com/labra/shaclex/blob/a8ce37c616d1db2e7cba112b08d0a0fb663debef/modules/srdfJena/src/main/scala/es/weso/rdf/jena/JenaMapper.scala#L75), it looks like only IntegerLiteral and DecimalLiteral are handled for numeric values. DoubleLiteral is not there and double values are converted to DatatypeLiteral probably.

2. minInclusive constraint is checked by calling [compareIntLiterals(n, _ <= _, minInclusiveError, "minInclusive")](https://github.com/labra/shaclex/blob/970b0e8186bbc04b13116ac4253e457b64f0062e/modules/shacl/src/main/scala/es/weso/shacl/validator/Validator.scala#L366) which relies on [checkNumeric](https://github.com/labra/shaclex/blob/970b0e8186bbc04b13116ac4253e457b64f0062e/modules/shacl/src/main/scala/es/weso/shacl/validator/Validator.scala#L591). In the checkNumeric function IntegerLiteral, DecimalLiteral and DoubleLiteral are checked and cast to int. If the value to be validated is not successfully converted to IntegerLiteral, DecimalLiteral or DoubleLiteral and its floor number inferior or equal to (<= ) to the provided value in the schema then the validation will fail. It is easy then to see that for values between [0,1] the cast to an int value will always give zero.

This is valid for minInclusive, maxInclusive, minExclusive, maxExclusive.

Any idea why all numeric values are cast to int when they are checked for minInclusive, maxInclusive, minExclusive, maxExclusive constraints ?

**Comment by labra** [comment]
Thanks for your report. You were right in both issues. I have repaired them, and it seems to work now as expected. 

As an example, you can check [the following link](http://rdfshape.weso.es/validate?data=%40prefix%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%20.%0A%40prefix%20%3A%20%20%20%20%20%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20.%0A%40prefix%20sh%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0A%40prefix%20xsd%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20.%0A%40prefix%20rdfs%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20.%0A%0A%3Aechotime%20%20a%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AQuantitativeValue%20%3B%0A%20%20%20%20%20%20%20%20schema%3AunitCode%20%20%22second%22%20%3B%0A%20%20%20%20%20%20%20%20schema%3Avalue%20%20%20%20%20%220.002996%22%5E%5Exsd%3Adouble%20.%0A%0A%3AbadEchoTime%20%20a%20%20%20%20%20%20%20%20%20%20schema%3AQuantitativeValue%20%3B%0A%20%20%20%20%20%20%20%20schema%3AunitCode%20%20%22second%22%20%3B%0A%20%20%20%20%20%20%20%20schema%3Avalue%20%20%20%20%20%220.0002996%22%5E%5Exsd%3Adouble%20.%0A&dataFormat=TURTLE&schema=prefix%20%3A%20%20%20%20%20%20%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20%0Aprefix%20sh%3A%20%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20%0Aprefix%20xsd%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0Aprefix%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0Aprefix%20rdfs%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0Aschema%3AQuantitativeValue%20a%20sh%3ANodeShape%2C%20rdfs%3AClass%20%3B%0A%20%20%20sh%3AnodeKind%20sh%3AIRI%20%3B%0A%20%20%20sh%3Aproperty%20%5B%0A%20%20%20%20sh%3Apath%20schema%3Avalue%20%3B%20%0A%20%20%20%20sh%3AminCount%201%3B%20%0A%20%20%20%20sh%3AmaxCount%201%3B%0A%20%20%20%20sh%3Adatatype%20xsd%3Adouble%20%3B%0A%20%20%20%20sh%3AminInclusive%200.001%20%3B%0A%20%20%20%20sh%3AmaxInclusive%200.01%20%3B%0A%20%20%5D%20.%0A&schemaFormat=Turtle&schemaEngine=SHACLex&triggerMode=TargetDecls&schemaEmbedded=false&inference=NONE&activeDataTab=%23dataTextArea&activeSchemaTab=%23schemaTextArea&activeShapeMapTab=%23shapeMapTextArea&&shapeMap=)
