### ISSUE TITLE
reducing command-line output

### ISSUE THREAD

**Issue by balhoff** [labra/shaclex#150]
When I run shaclex, it prints a large amount of output to the console. I tried various options that seem like they would eliminate output, but they don't seem to have an effect:

```bash
shaclex \
	--schema ../shapes/go-cam-shapes.shex \
	--schemaFormat SHEXC \
	--shapeMap ../shapes/go-cam-shapes.shapeMap \
	--data in.ttl \
	--trigger SHAPEMAP \
	--no-showLog \
	--no-showData \
	--no-showResult \
	--no-explain \
	--outFile out.shapeMap 
```

Is there a way to run quietly?

**Comment by labra** [comment]
You are right. Some of that command line is jts debug println's that have been kept there and should be cleaned. 

These days I am working on the library trying to add new features, so as a lateral effect I will try to remove those printlns. 

On the other hand, it would be good to some debug information on-demand, so I will see if I can just convert those lines to the logger.

**Comment by labra** [comment]
I have just published a new release where the println's have been removed. In principle, the only ouput generated should be through logging. The release is [0.1.25](https://github.com/labra/shaclex/releases/tag/0.1.25)

**Comment by balhoff** [comment]
This is great, thanks!
