### ISSUE TITLE
Heroku shaclex app not responsive

### ISSUE THREAD

**Issue by alexiskeely** [labra/shaclex#167]
Wasn't sure where to post this, but the shaclex app  on heroku is not accessible.

Thanks!

**Comment by labra** [comment]
It is possible. The shaclex heroku deployment is quite unstable as it depends on the free dynos provided by Heroku. 

A more official deployment is [http://rdfshape.weso.es](http://rdfshape.weso.es).

**Comment by alexiskeely** [comment]
Excellent, thank you!

**Comment by labra** [comment]
Notice that in the last month I have been working on a new front-end which will replace most of the features. Some features are not yet fully implemented. You can play with the new front-end [here](http://rdfshape.weso.es:8080/), once the new front-end is fully functional it will replace the old one.
