### ISSUE TITLE
Publish build artefacts on weso-releases

### ISSUE THREAD

**Issue by berezovskyi** [labra/shaclex#18]
I think this would solve the problems that arise from deploying artefacts into local .m2 repository like #16.

**Comment by berezovskyi** [comment]
Oops https://bintray.com/labra/maven/shaclex#

**Comment by labra** [comment]
Although as you could see, I had the binaries published to bintray, I prefer to reopen the issue as I am not sure that the original problem you had has been solved.

The binaries published were not the latest version of Shaclex (they corresponded to version 0.0.55) and I have just published 0.0.56. 

I would prefer to know if you have been able to call shaclex using this last version. Let me know if with the new binaries, you are able to call shaclex and it doesn't give you any problem.

**Comment by labra** [comment]
I have just published version 0.0.57 which uses Scala 2.12 compiler

**Comment by berezovskyi** [comment]
0.0.60 resolved the problem (#16)
