### ISSUE TITLE
Return all errors in data graph - SHACL

### ISSUE THREAD

**Issue by yashkhatri** [labra/shaclex#38]
The ShaclEx library should return all the errors in the data graph. 

Currently the SHACL validator of the ShaclEx library  returns only one constraint error in the data graph at random even though there are more errors in the data graph.

To understand this better:

​Example data graph:

​
```
@prefix ex:    <http://example.org/> .
@prefix oslc_data: <http://open-services.net/ns/servicemanagement/1.0/> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sam:   <http://www.sampledomain.org/sam#> .
@prefix oslc:  <http://open-services.net/ns/core#> .
<http://localhost:8080/SampleAdaptor/services/serviceProviders/1/aResources/1>
        a                       sam:AResource ;
        sam:aReferenceProperty  sam:AnotherResource ;
        sam:aSetOfDates         "2017-02-22T13:33:57.639Z"^^xsd:dateTime ;
        sam:aStringProperty     "Test" ;
        sam:anIntegerProperty   "1234"^^xsd:int​eger​ .
[ a              rdf:Statement ;
  rdf:object     sam:AnotherResource ;
  rdf:predicate  sam:aReferenceProperty ;
  rdf:subject    <http://localhost:8080/SampleAdaptor/services/serviceProviders/1/aResources/1>
] .
```

corresponding shacl shape graph:

```
@prefix ex:    <http://example.org/> .
@prefix oslc_data: <http://open-services.net/ns/servicemanagement/1.0/> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sam:   <http://www.sampledomain.org/sam#> .
@prefix oslc:  <http://open-services.net/ns/core#> .

ex:S    sh:property     [ sh:datatype  xsd:dateTime ;
                          sh:maxCount  0 ;
                          sh:minCount  0 ;
                          sh:predicate      sam:aSetOfDates
                        ] ;
        sh:property     [ sh:datatype  xsd:integer ;
                          sh:maxCount  1 ;
                          sh:minCount  1 ;
                          sh:predicate      sam:anIntegerProperty
                        ] ;
        sh:property     [ sh:datatype  xsd:string ;
                          sh:maxCount  0 ;
                          sh:minCount  0 ;
                          sh:predicate      sam:aStringProperty
                        ] ;
        sh:targetClass  sam:AResource .

```

In the above data graph there exists anIntegerProperty and aSetOfDates. But, according to shapes graph, the cardinality of these two properties should be 0.

The ShaclEx validation library SHOULD return maxCountError for both these properties. BUT, it returns only one error at random. Sometimes maxCountError for anIntegerProperty sometimes for aSetOfDates.

**Comment by yashkhatri** [comment]
@labra @darkLabra

**Comment by yashkhatri** [comment]
@berezovskyi  @jadelkhoury

**Comment by labra** [comment]
Yes, that's something I'm planning to repair in the near future. 

I was very busy in the last months but as soon as I find some time, I will adapt the computation model to collect all errors. 

The reason for returning only the first error was to increase performance in case of very big RDF data to avoid generating all errors. 

Currently SHACL specification says that implementations must potentially be able to generate all errors, but that sometimes they don't need to generate all errors. My first attempt will be to add a flag so users can choose if they want all-errors behavious or first-error-stop behaviour.

**Comment by labra** [comment]
I started to work on this in branch [shacl-allResults](https://github.com/labra/shaclex/tree/shacl_allResults)

**Comment by yashkhatri** [comment]
Hi!

The link you gave is broken. When are you planning to release this bug-fix. Thank you for investing time in it.

**Comment by berezovskyi** [comment]
Yes, perhaps you forgot to push the branch?

**Comment by labra** [comment]
Ops, I had done the job in that specific branch but once I finished it, I just merged to master and deleted the branch. You can see the PR [here](https://github.com/labra/shaclex/pull/52).

The example from @yashkhatri works now (after updating the name of the properties from sh:predicate to sh:path and adding the type declaration sh:NodeShape). 

You can see it working [here](http://shaclex.herokuapp.com/validate?data=%40prefix%20ex%3A%20%20%20%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20.%0A%40prefix%20oslc_data%3A%20%3Chttp%3A%2F%2Fopen-services.net%2Fns%2Fservicemanagement%2F1.0%2F%3E%20.%0A%40prefix%20sh%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0A%40prefix%20rdf%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20.%0A%40prefix%20xsd%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20.%0A%40prefix%20dcterms%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%20.%0A%40prefix%20rdfs%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20.%0A%40prefix%20sam%3A%20%20%20%3Chttp%3A%2F%2Fwww.sampledomain.org%2Fsam%23%3E%20.%0A%40prefix%20oslc%3A%20%20%3Chttp%3A%2F%2Fopen-services.net%2Fns%2Fcore%23%3E%20.%0A%0A%3Chttp%3A%2F%2Flocalhost%3A8080%2FSampleAdaptor%2Fservices%2FserviceProviders%2F1%2FaResources%2F1%3E%0A%20%20%20%20%20%20%20%20a%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sam%3AAResource%20%3B%0A%20%20%20%20%20%20%20%20sam%3AaReferenceProperty%20%20sam%3AAnotherResource%20%3B%0A%20%20%20%20%20%20%20%20sam%3AaSetOfDates%20%20%20%20%20%20%20%20%20%222017-02-22T13%3A33%3A57.639Z%22%5E%5Exsd%3AdateTime%20%3B%0A%20%20%20%20%20%20%20%20sam%3AaStringProperty%20%20%20%20%20%22Test%22%20%3B%0A%20%20%20%20%20%20%20%20sam%3AanIntegerProperty%20%20%201234%20.%0A&dataFormat=TURTLE&schema=%40prefix%20ex%3A%20%20%20%20%3Chttp%3A%2F%2Fexample.org%2F%3E%20.%0A%40prefix%20oslc_data%3A%20%3Chttp%3A%2F%2Fopen-services.net%2Fns%2Fservicemanagement%2F1.0%2F%3E%20.%0A%40prefix%20sh%3A%20%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0A%40prefix%20rdf%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%20.%0A%40prefix%20xsd%3A%20%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%20.%0A%40prefix%20dcterms%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%20.%0A%40prefix%20rdfs%3A%20%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%20.%0A%40prefix%20sam%3A%20%20%20%3Chttp%3A%2F%2Fwww.sampledomain.org%2Fsam%23%3E%20.%0A%40prefix%20oslc%3A%20%20%3Chttp%3A%2F%2Fopen-services.net%2Fns%2Fcore%23%3E%20.%0A%0Aex%3AS%20%20%20%20a%20sh%3ANodeShape%20%3B%0A%20%20%20%20%20%20%20%20sh%3Aproperty%20%20%20%20%20%5B%20sh%3Adatatype%20%20xsd%3AdateTime%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3AmaxCount%20%200%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3AminCount%20%200%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3Apath%20%20%20%20%20%20sam%3AaSetOfDates%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20sh%3Aproperty%20%20%20%20%20%5B%20sh%3Adatatype%20%20xsd%3Ainteger%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3AmaxCount%20%201%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3AminCount%20%201%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3Apath%20%20%20%20%20%20sam%3AanIntegerProperty%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20sh%3Aproperty%20%20%20%20%20%5B%20sh%3Adatatype%20%20xsd%3Ainteger%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3AmaxCount%20%200%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3AminCount%20%200%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20sh%3Apath%20%20%20%20%20%20sam%3AaStringProperty%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%20%3B%0A%20%20%20%20%20%20%20%20sh%3AtargetClass%20%20sam%3AAResource%20.%0A%0A&schemaFormat=Turtle&schemaEngine=SHACLex&triggerMode=TargetDecls&schemaEmbedded=false&inference=NONE&shapeMap=).

I didn't want to close the issue yet until I checked the feature using the SHACL test suite. To that end, we are working on generating the ValidationReport following the SHACL recommendation.

One problem that needs to be solved is converting the result structure (called result shape map) to validation report results. I hope I can work on this feature soon.

**Comment by yashkhatri** [comment]
Hi!

 "_One problem that needs to be solved is converting the result structure (called result shape map) to validation report results. I hope I can work on this feature soon_."

Would be nice to know that status of this. Is this implemented now?

**Comment by labra** [comment]
Not yet...I was involved in other tasks and couldn't tackle it. It is really one of the first topics in my TODO list but the next two weeks I will have a lot of teaching duties...

I will try to devote time to it as soon as possible. One preliminary step I did was to be able to read SHACL's manifest files which were slightly different from my original proposal. I needed this previous step in order to be able to pass the SHACL test-suite...which is my final goal.

**Comment by yashkhatri** [comment]
Hi @labra I was using 0.0.63 version of shaclex library (https://dl.bintray.com/labra/maven/es/weso/shaclex_2.12/) in our java project. 

This issue#38 is still open. However, I would like to use the feature of getting all the errors in data graph if it is implemented and released. So my question is; does any of the version (0.0.65, 0.0.66, 0,0,67) contains this feature?

**Comment by labra** [comment]
The latest release [0.074](https://dl.bintray.com/labra/maven/es/weso/shaclex_2.12/0.0.74/) already has implemented that feature. 

I prefer to keep the issue open because I didn't have time to check all the tests in the SHACL testsuite.

**Comment by labra** [comment]
As all the tests in the SHACL test-suite have passed, I think we can close this issue.
