### ISSUE TITLE
Is TotalDigits not implemented?

### ISSUE THREAD

**Issue by steotia** [labra/shaclex#62]
For schema as
```
PREFIX sample: <http://example.com/voc/teacher/1.0.0/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ex: <http://ex.example/#>

sample:udiseNumberConstraint xsd:integer TotalDigits 11

sample:UdiseNumberShape {
  sample:udiseNumber @sample:udiseNumberConstraint
}
```
and data as 
```
@prefix sample: <http://example.com/voc/teacher/1.0.0/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sh: <http://www.w3.org/ns/shacl#>

sample:1234 a sample:School ;
  sample:udiseNumber 1 .

sample:UdiseNumberShape sh:targetNode sample:1234 .
```

validations says "noncomformant" with reason as

```
"reason" : "Error: Node 1 has no shape sample:udiseNumberConstraint\nErrors: Error: Not implemented checkFacet: TotalDigits(11)"
```

Is it correct that it is unimplemented?
Also, is there a way to check which facets are implemented? And is there a workaround? I tried using maxinclusive but it can't take a large number.

**Comment by labra** [comment]
Ops, you are right, I had forgotten to implement it. 

I will try to implement it in the following days. 

I also updated issue #4 to reflect the current status of the rest of facets. In principle, as far as I remember, the rest of facets are implemented.

**Comment by labra** [comment]
Implemented totalDigits and fractionDigits

**Comment by steotia** [comment]
Great! Quick turn around, appreciate it! @labra
