### ISSUE TITLE
Need Release Tags

### ISSUE THREAD

**Issue by steotia** [labra/shaclex#79]
#62 was fixed, but not available through any of the current release tags. Also, master does not build successfully. I believe version 66 of the library is available in bintray. Could you please provide matching release tags for released binaries (or at least for the release version which resolves #62 )

**Comment by labra** [comment]
Indeed, you are right. Until now I was not very careful about the different releases. 

I will try to be more careful with the release process and publication.

**Comment by labra** [comment]
I reviewed to see if the master builds succesfully and it does. I am using Travis Continuous Integration and you can see that the latest commit builds successfully [here](https://travis-ci.org/labra/shaclex).

I have also added tag [Release 0.0.66](https://github.com/labra/shaclex/releases/tag/v0.0.66), to the latest master code.

I will try to be more careful to publish releases and document which issues have been solved in future releases.

**Comment by steotia** [comment]
thanks!
