### ISSUE TITLE
[HELP] Validations on closed shapes

### ISSUE THREAD

**Issue by steotia** [labra/shaclex#80]
with a shex file as 
```
PREFIX sample: <http://example.com/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
sample:AShape CLOSED {
    a [sample:A] ;
    sample:b @sample:BShape
}
sample:BShape CLOSED {
    a [sample:B] ;
    sample:c xsd:string
}
```
and data as 
```
@prefix sample: <http://example.com/> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
sample:a001 a sample:A ;
    sample:b sample:b001 .
sample:b001 a sample:B ;
    sample:c "something c" .
sample:AShape sh:targetNode sample:a001 .
```
validation fails with message
```
[info] Error: Closed shape. But rest ^sample:b is not in List(Inverse(<http://www.w3.org/ns/shacl#targetNode>)) or List()
```
It is not clear to me why validation should fail? How can I modify the data or the shex definitions to make validations pass on both closed shapes?

**Comment by labra** [comment]
I have been trying the example in the online validator and it seems to work. Did you try it in the online validator?

By the way, I wanted to create a permalink and it is failing, but that is a different issue.

**Comment by steotia** [comment]
oh ya, it is running in the online validator but when I run it via the Scala CLI App as ```run -e ShEx -s ./a.shex --schemaFormat ShExC -d ./a.record``` it gives me the error I have mentioned earlier.

Could you try that too pls?

Also, is the online validator, having a client side JavaScript validator or is it hitting a backend server running the Scala library?

**Comment by steotia** [comment]
I tried to inspect traffic and didn't see any calls being made to a server so I am assuming that the validation is happening in JavaScript. And the permalink is https://rawgit.com/shexSpec/shex.js/master/doc/shex-simple.html?schema=PREFIX%20sample%3A%20%3Chttp%3A%2F%2Fexample.com%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0Asample%3AAShape%20CLOSED%20%7B%0A%20%20%20%20a%20%5Bsample%3AA%5D%20%3B%0A%20%20%20%20sample%3Ab%20%40sample%3ABShape%0A%7D%0Asample%3ABShape%20CLOSED%20%7B%0A%20%20%20%20a%20%5Bsample%3AB%5D%20%3B%0A%20%20%20%20sample%3Ac%20xsd%3Astring%0A%7D&data=%40prefix%20sample%3A%20%3Chttp%3A%2F%2Fexample.com%2F%3E%20.%0A%40prefix%20sh%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fshacl%23%3E%20.%0Asample%3Aa001%20a%20sample%3AA%20%3B%0A%20%20%20%20sample%3Ab%20sample%3Ab001%20.%0Asample%3Ab001%20a%20sample%3AB%20%3B%0A%20%20%20%20sample%3Ac%20%22something%20c%22%20.%0A&manifestURL=..%2Fexamples%2Fmanifest.json&shape-map=sample%3Aa001%40sample%3AAShape&interface=human&regexpEngine=threaded-val-nerr
