### ISSUE TITLE
Improve the logging system

### ISSUE THREAD

**Issue by labra** [labra/shaclex#84]
At this moment, the project uses a quite dirty way to log. Sometimes, for debugging reasons, it even uses temporary println's which after the bug is fixed remain in the code. As nobody complained, I tend to leave them until I remove them later...anyway, it would be better to clean those as well and implement a better logging feature for debugging.

One nice feature would be to allow to generate logs to some external system like [Apache Kafka](https://kafka.apache.org/). I will let this issue open until we have time to implement such a system.

**Comment by yashkhatri** [comment]
I was about to open this issue. I am using this library (version 0.0.63) from java. I am getting a lot of unwanted logs on the console which in turn slows down my application further. Is there a way to disable these logs or I have to live with it unless it is fixed in a new release?

**Comment by berezovskyi** [comment]
We use SLF4J in almost all projects, so it would be better to use something that integrates with it. @labra would you think something like https://github.com/lightbend/scala-logging or https://github.com/Log4s/log4s would work (my knowledge of the Scala libraries is really basic)? I can look at next week and submit my progress as a PR for your review.

**Comment by berezovskyi** [comment]
On another look, the code is full of println's, so maybe the first step would be to replace all println's with `logger.debug` and then see if the levels should be tuned etc. I can do it over the weekend to get started with the first PR.

**Comment by labra** [comment]
Indeed, I use println's for quick debug, but sometimes forget to remove them. 

In principle, all those println's could be removed or replaced by `logger.debug` calls. I will appreciate if you want to do it, and create a PR as these days I have lots of teaching duties.
