### ISSUE TITLE
Convert Shex to RDF

### ISSUE THREAD

**Issue by steotia** [labra/shaclex#87]
Is there a public implementation which can be used to convert Shex to RDF? https://github.com/labra/shaclex/tree/master/modules/shex/src/main/scala/es/weso/shex/shexR talks about this conversion but I am not sure how to use the library.

I am working in Java, using `shaclex_2.12` and calling the Scala code from my Java code.

**Comment by steotia** [comment]
Also, is there a way I can programmatically manipulate the Shape Expressions (after parsing out the ShEx file) - essentially have a dictionary of Shape Expressions from which I can create new Expressions to match incoming update data (the incoming data is a PATCH update, so will contain only a subset of fields and thus will fail validation if tested against the master ShEx).
In the absence of that, I am thinking of writing the same logic by converting ShEx to RDF and then back to ShEx.

**Comment by labra** [comment]
About the first question, you may find useful a standalone Java repository that I created to show how the Shaclex library can be invoked from Java. 

The repository is called [shexjava](https://github.com/labra/shexjava) and I have just included a new option to the main program that shows the ShEx Schema in some output format specified. In the README, I included an example on how it can be used to transform a ShEx compact file to a Turtle file using ShExR. 

So it is quite easy to load a Schema and serialize it to RDF. The serialization code, is done through the shexR code that you linked.

About manipulating Shape Expressions programmatically, it is also possible, although I am not sure if it would be the best way as it may couple your code to the internal representation of Shape Expressions. Anyway, if you want to do it, the Shape Expressions abstract syntax is defined [here](https://github.com/labra/shaclex/blob/master/modules/shex/src/main/scala/es/weso/shex/shex.scala). 

The abstract syntax is almost a direct encoding from the [ShEx spec](http://shex.io/shex-semantics/index.html) so in principle, it should be as stable as the language itself.

**Comment by steotia** [comment]
Thanks, I will try and re-open if it needs to be.
