### ISSUE TITLE
How can I do a \pL Pattern match for validating against strings?

### ISSUE THREAD

**Issue by steotia** [labra/shaclex#97]
```
PREFIX opensaber: <http://example.com>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org>

opensaber:isAName LITERAL /\\p{L}+/

opensaber:TeacherShape {
	a [opensaber:Teacher] ;
    schema:name @opensaber:isAName
}
```
(1) I would like to do a ```\\p{L}``` type match. Is it possible? I am trying to validate International names in Unicode.
(2) Also, is ```opensaber:isAName LITERAL /\\p{L}+/``` the right way to validate the Pattern string facet? I was initially trying ```opensaber:isAName xsd:string Pattern /\\p{L}+/``` but that wasn't working. Is there documentation which I have missed which describes using ```Pattern```. I got to my line by digging into the test code.

**Comment by labra** [comment]
I was checking the code and it works. 

Maybe, however, if you want to check that all characters from the value of `schema:name` are unicode letters, you must add `^` and `$` characters to indicate that the string must start and end by those characters and that any other code inside the string must be a unicode letter using the `\\p{L}+` expression. 

You can see your example [here](https://goo.gl/GdbQ54).

About your second question, the right way to declare regular expressions is as you did, with the syntax `/regex/`. It is true that in some previous ShEx versions, we used the `Pattern` syntax, but it was later replaced by the back slashes.

**Comment by steotia** [comment]
Great! I was trying the other RDF validators but they seem to not work. Thanks a ton for trying out.

About the LITERAL keyword, maybe a bit of documentation would help. I had to pick it out by digging into the code, but did I miss some documentation from my side?
